FROM alpine-jdk:base
MAINTAINER lanu
COPY files/config-service.jar /opt/lib/
RUN mkdir /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/config-service.jar"]
VOLUME /var/lib/config-repo
EXPOSE 8888

