version: '3'
services:
    config-service:
        container_name: config-service
        build:
            context: .
            dockerfile: Dockerfile-configservice
        image: config-service:latest
        expose:
            - 8888
        ports:
            - 8888:8888
        networks:
            - emp-network
    registry-service:
        container_name: eureka-service
        build:
            context: .
            dockerfile: Dockerfile-registryservice
        image: registry-service:latest
        depends_on:
            - config-service
        environment:
            - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
        entrypoint: /opt/bin/registry-service-entrypoint.sh
        expose:
            - 8761
        ports:
            - 8761:8761
        networks:
            - emp-network
networks:
    emp-network:
        driver: bridge


