FROM alpine-jdk:base
MAINTAINER lanu
COPY files/config-service.jar /opt/lib/
COPY config-server/src/main/resources/shared /application-config/shared/
COPY files/config-service-entrypoint.sh /opt/bin/config-service-entrypoint.sh
RUN chmod 755 /opt/bin/config-service-entrypoint.sh
EXPOSE 8000

