FROM alpine-jdk:base
MAINTAINER lanu
COPY files/registry-service.jar /opt/lib/
COPY files/registry-service-entrypoint.sh /opt/bin/registry-service-entrypoint.sh
RUN chmod 755 /opt/bin/registry-service-entrypoint.sh
EXPOSE 8761

