FROM alpine-jdk:base
MAINTAINER lanu
COPY files/config-service.jar /opt/lib/
COPY application-config/shared /application-config/shared
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/config-service.jar"]
VOLUME /var/lib/config-repo
EXPOSE 8888

