spring:
  application:
    name: account-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 1234
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /accounts
  port: 8003

feign:
  hystrix:
    enabled: true
