spring:
  application:
    name: account-service

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 1234
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /accounts
  port: 8003

feign:
  hystrix:
    enabled: true
