spring:
  data:
    mongodb:
      host: localhost #should be localhost (without Docker)
      port: 27017
      username: oauth-user
      password: password
      database: oauth-db
  application:
    name: auth-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

server:
  servlet:
    context-path: /uaa
  port: ${PORT:0}
