spring:
  data:
    mongodb:
      host: mongo-oauth #should be localhost (without Docker)
      port: 27017
      username: oauth-user
      password: password
      database: oauth-db
  application:
    name: auth-service

server:
  servlet:
    context-path: /uaa
  port: 8002
