spring:
  application:
    name: employee-search-service

server:
  servlet:
    context-path: /employee
  port: 8004

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: employee-service
      clientSecret: 1234
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      grant-type: client_credentials
      scope: server
