spring:
  application:
    name: registry-service #name of the application

server:
  port: 8001 #the default port used for eureka servers

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: false
    fetch-registry: false
