spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared #tells spring where to locate the config files
  profiles:
    active: native #we are using native because the config server uses a git repo by default
  security:
    user:
      password: 1234 #the password which apps will use to access its configurations

server:
  port: 8000 #the port where the config-server will be accessible

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
